In [1]:
import numpy as np
import matplotlib.pyplot as plt
import random
from mpl_toolkits.mplot3d import Axes3D
from collections import defaultdict
# %matplotlib widget

# Setup of a big dict.


In [2]:
n = 4

In [3]:
fibre_list = list()
#Generate all x,y,z fibres
for i in range(n):
    for j in range(n):
        tmp_fibre = list()
        tmp_fibre1 = list()
        tmp_fibre2 = list()
        for k in range(n):
            tmp_fibre.append( (i,j,k) ) 
            tmp_fibre1.append( (k,i,j) ) 
            tmp_fibre2.append( (j,k,i) ) 
        fibre_list.append(tmp_fibre)
        fibre_list.append(tmp_fibre1)
        fibre_list.append(tmp_fibre2)


#Generate diagonal fibres
for k in range(n):
    tmp_fibre = list()
    tmp_fibre1 = list()
    tmp_fibre2 = list()
    tmp_fibre3 = list()
    tmp_fibre4 = list()
    tmp_fibre5 = list()
    for i in range(n):
        #xz plane 
        tmp_fibre.append( (n-i-1,k,i) )
        tmp_fibre1.append( (i,k,i) )

        #xy plane
        tmp_fibre2.append( (i,n-i-1,k) )
        tmp_fibre3.append( (i,i,k) )

        #yz plane
        tmp_fibre4.append( (k,i,n-i-1) )
        tmp_fibre5.append( (k,i,i) )
    # print(tmp_fibre1)
    fibre_list.append(tmp_fibre)
    fibre_list.append(tmp_fibre1)
    fibre_list.append(tmp_fibre2)
    fibre_list.append(tmp_fibre3)
    fibre_list.append(tmp_fibre4)
    fibre_list.append(tmp_fibre5)

#Global diagonals
tmp_fibre = list()
tmp_fibre1 = list()
tmp_fibre2 = list()

for i in range(n):
    tmp_fibre.append( (i,i, i))
    tmp_fibre1.append( (n-1-i,i, i))
    tmp_fibre2.append( (i,n-1-i, i))
    tmp_fibre3.append( (i,i, n-1-i))

fibre_list.append(tmp_fibre)
fibre_list.append(tmp_fibre1)
fibre_list.append(tmp_fibre2)
fibre_list.append(tmp_fibre3)

print(len(fibre_list))
####

big_dict = dict()


for i in range(n):
    for j in range(n):
        for k in range(n):
            big_dict[f'{i}{j}{k}'] = [ fibre for fibre in fibre_list if (i,j,k) in fibre ]

# print(len(big_dict))

# fibre_rank = dict()
# for fibre in fibre_list:
#     #Player and rank
#     fibre_rank[f"{fibre}"] = [None,0]
# big_dict['330']

76


# Board

In [11]:

class Board():
    def __init__(self, n = 4, dimension = 3, big_dict =  big_dict, fibre_list = fibre_list):
        ''' 
        n = size of board (n x n x n) if dimension = 3.
        dimension = dimension of board
        
        Generate ALL possible fibres in a list where e.g. list[1] =  ( (0,0), (0,1), (0,2) ).
        Each fibre should only occur once in the list.
        Then create a dictionary with (x,y,z) as the index and a list of indices for fibres that intersect this point. also add a rank to each list
        );
        bigus_dict = { (0,0,0) : [0,2,7,65] }
        
        Next we only have to check these fibres for a win.
        
        Instead of checking all elements of each fibre, we create a another dict:
        
        fibre_rank = { 0: [0,--1] , ... }
        
        if the rank is -1, ignore this index and increase unwinnable fibres by 1. else increase each index of the fibres by 1. If a fibre has rank n we have a win.
        
        if unwinnable_fibres = total fibres, the game is a draw
        
        '''
        self.n = n
        self.dimension = dimension
        self.board = np.zeros([n,n,n])
        
        self.impossible_row_count = 0
        self.big_dict = big_dict
        
        self.fibre_rank = dict()
        for fibre in fibre_list:
            #Player and rank
            self.fibre_rank[f"{fibre}"] = [None,0]
        #This could be outsourced.
        
            
        # a = np.zeros([n,n])
        # for k in range(n):
        #     for i in range(n):
        #         for j in range(n):
        #             a[i,j] = len(big_dict[f'{i}{j}{k}'])
        #     print(k)
        #     print(a)
            
    def __repr__(self):
        for k in range(n):
            for j in range(n):
                print(f" "* (n -k),end='')
                print(self.board[k][j])
        return ''
    
    def reset(self):
        self.__init__()
        
    def board_status(self):
        print(f'Non zero elements on board: {np.count_nonzero(self.board)}')
    
    def board_vector(self):
        '''returns a vector with the board representation'''
        reshape = np.reshape(self.board, (-1,1))
        return reshape

    
    def addmove(self, player, coordinates ):
        '''
        add move and checks whether there is a win or a draw.
        '''
        x = coordinates[0]
        y = coordinates[1]
        z = coordinates[2]
        
        str_coords = str(x) + str(y) + str(z)
        
        #Check if valid move...
        
        self.board[n-z-1,n-y - 1,x] = player
        
        #Update all fibreranks that intersect with the given point
        for fibre in self.big_dict[str_coords]:
            #fibre is 1 fibre intersecting the given point.
            # print(fibre)
            
            tmp_rank = self.fibre_rank[f'{fibre}']
            
            if tmp_rank[1] == -1:
                pass
                
            # nobody has claimed this fibre
            elif not tmp_rank[0]:
                self.fibre_rank[f'{fibre}'] = [player, 1]
                
            # The fibre has been claimed by another asailant.
            elif tmp_rank[0] != player:
                # print("blocked!")
                self.fibre_rank[f'{fibre}'] = [None,-1]
                self.impossible_row_count += 1
                if self.impossible_row_count == self.n * self.n * 3 + 6*self.n + 3:
                    # print('DRAW')
                    return False
            # this is your fibre, increase its rank
            else:
                self.fibre_rank[f'{fibre}'][1] += 1
                if self.fibre_rank[f'{fibre}'][1] == 4:
                    #thou has won.
                    # print(f'WIN player {player}')
                    # print(f'win player {player}: {fibre} rank: { self.fibre_rank[f"{fibre}"][1] }')
                    return True
                
            
            # print(self.fibre_rank[f'{fibre}'] )
    
    def addmove_vector(self, player, vec_coords) -> None:
        ''' Takes in a vector as move input, this is usefull for the AI.
        It then processes this vector and treats it as a normal cartesian input.
        '''
        
        return self.addmove(player,self.vector_to_cartesian(vec_coords))
    
    def vector_to_cartesian(self, vec_coords):
        reshape = np.reshape(vec_coords, (self.n,self.n,self.n))
        
        #Get coordinates
        move = np.argwhere(reshape != 0)[0]
        
        #Convert coordinates to cartesian coordinates.
        tmp_x = move[0]
        move[0] = move[2]
        move[1] = self.n - move[1] - 1
        move[2] = self.n - tmp_x - 1
        return tuple(move)
    
    def impossible_moves(self):
        a = np.argwhere(self.board != 0)
        a0 = a[:,0].copy()
        a1 = a[:,1].copy()
        a2 = a[:,2].copy()
        b = np.zeros_like(a)

        b[:,0] = a2
        b[:,1] = n - a1 - 1
        b[:, 2] = n - a0 -1
        return tuple(map(tuple,b))
    
    def impossible_moves_vector(self):
        '''returns all impossible moves in vector representation'''
        return np.reshape(self.board != 0, (-1,1))
    
    def possible_moves(self):
        a = np.argwhere(self.board == 0)
        a0 = a[:,0].copy()
        a1 = a[:,1].copy()
        a2 = a[:,2].copy()
        b = np.zeros_like(a)

        b[:,0] = a2
        b[:,1] = n - a1 - 1
        b[:, 2] = n - a0 -1
        return tuple(map(tuple,b))
    




# Players

In [12]:
##  HERE we define the main player class. It's simple, only needing a name.
class Player:
    """Generate a tictactoe player.

    These operatioons are supported:
    * `choice`, to choose the next move based of an inputed Board.
    """

    def __init__(self,name:str):
        """Give player their name.
        """
        self.wincount = 0
        self.losscount =0 
        self.drawcount = 0
        self.name=name
                
    def __repr__(self) -> str:
        """Return player name. Computer representation.
        """
        return str(self.name)
    def add_win(self):
        self.wincount += 1
    def add_loss(self):
        self.losscount += 1
    def add_draw(self):
        self.drawcount += 1
    def resetcount(self):
        self.wincount = 0
        self.losscount = 0 
        self.drawcount = 0

# implement DL model
evolutionary dl. Give the model some parameters to adjust, instantiate a random instance, construct random 'gausian' balls around this instance (noise in parameters).
Make the different instances play 100 games against each other (somehow, make winners compete against winners).
After 1 round generate new instance center and repeat algorithm.

The neural net takes in a board position vector $x_0$ of size (n^3, 1), then multiplies this vector $x_0$ by weight matrix $w_0$ and adds a bias $b_0$ , then pass all that through a activation function $A(x)$ yielding a new output vector $x_1 = A(w_0 * x_0 + b_0)$. We add some more of these layers.
Finaly the output shoud be a vector of size (n^3,1).


reward/utility function:
- win: 2 * n - moves 
- loss: -2 *n - moves
- draw: - moves

## Neural player

In [13]:
class neural_player(Player):
    def __init__(self,name:str, weights = None, biases = None):
        """Give player their name. Record callable function for choice
        """
        self.name = name
        self.resetcount()
        
        self.layers = [n**3,128,48,n**3]
        self.dropout = [1,1,1,1]
        if weights is None and biases is None:
            assert np.shape(weights) == np.shape(biases), 'Shapes of w & b not equal!'
                
            self.weight = []
            self.bias = []

            for index in range(len(self.layers) - 1) :

                self.weight.append(np.random.rand(self.layers[index + 1], self.layers[index]))

                self.bias.append( np.random.rand(self.layers[index + 1],1))
        else:
            self.weight = weights
            self.bias = biases
    def save_npy(self):
        np.save(f'{self.name}_weights', self.weight )
        np.save(f'{self.name}_biases', self.bias )

    def activation_function(self, x):
        return np.maximum(0,x)

    def choice(self,board:Board):
        prev_out= None
        for index in range(len(self.layers) - 1) :
            if prev_out is None:
                prev_out = board.board_vector()
                

            output = self.activation_function( np.matmul(self.weight[index], prev_out) + self.bias[index] )
            
            dropout_keep_value = self.dropout[index]
            mask = np.random.binomial(1,dropout_keep_value,size=np.shape(output) )
            output = output * mask
            # print(f'Layer {index}, input= {np.shape(prev_out)} output = {np.shape(output)}')
            prev_out = output
            
        

        mask = board.impossible_moves_vector()
        output[mask] = 0 #only select the output nodes that are actually possible.
        
        
        a = np.zeros([n**3])
        a[np.argmax(output)] = 1 #Select the output node w the highest value.
        return a
    #This needs to get cleaned
    def add_win(self, moves: int):
        self.score += 2 *n - moves
        self.wincount += 1

    def add_loss(self, moves:int):
        self.score += -2 *n - moves
        self.losscount += 1
        
    def add_draw(self, moves:int):
        self.score += - moves
        self.drawcount += 1
    def resetcount(self):
        self.score = 0
        self.wincount= 0
        self.losscount = 0
        self.drawcount = 0
     

## Random player

In [14]:
   
class random_player(Player):
    def __init__(self,name:str):
        """Give player their name. Record callable function for choice
        """
        self.name = name

        self.resetcount()
    def choice(self,board:Board):
        choice_coords = tuple(random.choice(board.possible_moves()))
        x = choice_coords[0]
        y= choice_coords[1]
        z = choice_coords[2]
        
        tmp = np.zeros( (board.n, board.n, board.n)) 
        tmp[n-z-1,n-y - 1,x] = 1
        return np.reshape(tmp, (-1,1))
    
    def add_win(self, moves: int):
        self.score += 2 *n - moves
        self.wincount += 1

    def add_loss(self, moves:int):
        self.score += -2 *n - moves
        self.losscount += 1
        
    def add_draw(self, moves:int):
        self.score += - moves
        self.drawcount += 1
    def resetcount(self):
        self.score = 0
        self.wincount= 0
        self.losscount = 0
        self.drawcount = 0
    

# Start competition

In [15]:
import time




def start_competition(player1, player2, iterations = 5000, verbose = False):
    board = Board()
    player_list = [player1, player2]
    matchcount = 0

    curr_index = 0
    uncurr_index = 1

    tic = time.perf_counter()
    player1.resetcount()
    player2.resetcount()
    
    moves =0 # keep track of the amount of moves in a game, this should be outsourced to the board class.
    total_moves = 0
    while matchcount != iterations:

            # print(f"\rIter {asdf} ", end="")


            
            choice = player_list[curr_index].choice(board)
            result = board.addmove_vector(curr_index +1 ,choice)

            # result = board.addmove(curr_index +1 ,player_list[curr_index].choice(board))
            # print(f'Player: {curr_index + 1}, choice: {choice}', end='')
            # board.board_status()
            # print(board)

            if result is None: #no draw or win
                tmp =  curr_index
                curr_index = uncurr_index
                uncurr_index = tmp
                moves += 1
                
            elif result: #win for player :  player_list[curr_index]
                player_list[curr_index].add_win(moves)
                player_list[uncurr_index].add_loss(moves)
                matchcount +=1
                board.reset()
                total_moves += moves
                moves = 0


            else: #draw
                player_list[curr_index].add_draw(moves)
                player_list[uncurr_index].add_draw(moves)
                matchcount += 1
                board.reset()
                total_moves += moves
                moves = 0
                # print("ELSE")
                # print(f'MATCH {matchcount}')

        # print(board) 
    if verbose:
        print()
        print(f"{player1}, score= {player1.score}, wincount = {player1.wincount}, losscount = {player1.losscount}, drawcount = {player1.drawcount}, avg moves: {total_moves / iterations}")
        print(f"{player2}, score= {player2.score}, wincount = {player2.wincount}, losscount = {player2.losscount}, drawcount = {player2.drawcount}, avg moves: {total_moves / iterations}")
        toc = time.perf_counter()
        print(f"Took {toc - tic:0.4f} seconds")
        
    if player1.score > player2.score:
        return [player1, player1.score]
    else:
        return [player2,player2.score]
    
    




## Find a random neural player that out performs the random player

In [16]:
# randomPlayer =random_player("player_rand")
# iterations = 3
# result_dict = dict()
# for i in range(iterations):
#     playertmp = neural_player(f'Player_{i}')
        
#     winning_player = start_competition(randomPlayer, playertmp,5000)
#     if winning_player[0].name != 'player_rand':
#         result_dict[i] = winning_player
# best_player = None
# best_player_score = 0
# best_player_index = None
# for key,val in result_dict.items():
#     if val[1] > best_player_score and val[0].name != 'player_rand':
#         best_player = val[0]
#         best_player_score = val[1]
#         best_player_index = key
# print(best_player, best_player_score)


In [17]:
# randomPlayer =random_player("player_rand")

# player_to_test = result_dict[best_player_index][0]
# start_competition(player_to_test,randomPlayer, 3000)


In [18]:
# player_to_test.save_npy()

# Take the best neural_player and mutate it.
1. Load initial weight & biases
2. mutate these weights & biases by a 'tiny' amount using some kind of normal distribution
 - This will yield say 20 mutations, instatiate 20 players w these weights and baises
3. Make these 20 + 1 players compete against each other, pick the one with the best score.
4. repeat step 2, 100 times
5. profit


Q: How do we let 21 players compete against each other?  thats 21 choose 2 = 210 matches.
A: we need a different strategy for holding competitions


## 1. Load initial weights & biases

In [19]:

initial_weights = np.load("Player_85_weights.npy", allow_pickle=True)
initial_biases = np.load("Player_85_biases.npy", allow_pickle=True)
initial_player = neural_player( "p2", initial_weights, initial_biases)


## 2. Mutate 

In [20]:
mutated_dict = dict() # Contains mutated weights and biases


def gen_mutated(amountofmutations: int, initial_weights, initial_biases, learning_rate = 0.1):
    """
    Returns an array with mutated weights and biases
    """ 
    for i in range(amountofmutations):
        # print(f'Mutating player number {i}')

        tmp_weights = list()
        tmp_biases = list()

        mutated_dict[i] = dict()

        for j in range(len(initial_weights)):
            a = np.shape(initial_weights[j])
            b = np.shape(initial_biases[j])
            tmp_weights.append( initial_weights[j] +  learning_rate * np.random.random(a ) )
            tmp_biases.append( initial_biases[j] + learning_rate * np.random.random(b ) )
        mutated_dict[i]['weights'] = tmp_weights 
        mutated_dict[i]['biases'] = tmp_biases 
    #Also add the original without mutations

    tmp_weights = list()
    tmp_biases = list()
    
    mutated_dict[len(mutated_dict)-1] = dict()
    for j in range(len(initial_weights)):
        a = np.shape(initial_weights[j])
        b = np.shape(initial_biases[j])
        tmp_weights.append( initial_weights[j]  )
        tmp_biases.append( initial_biases[j]  )
    mutated_dict[len(mutated_dict)-1]['weights'] = tmp_weights 
    mutated_dict[len(mutated_dict)-1]['biases'] = tmp_biases 
    return mutated_dict




## 3. Make the ants fights amongst themselfs and pick the strongest one

Ideally we would like to test all mutated player against each other. Since this is not feasible we hold a competition.


In [21]:
def obtain_strongest_player(mutated_dict: dict):
    """
    Yield the strongest player via a knock out competition
    """
    
    contenders = list()
    while True:

        if len(contenders) == 0:
            for key,value in mutated_dict.items():
                # print(key)
                tmp_player = neural_player(f'{key}', value['weights'], value['biases'])

                contenders.append(tmp_player)
        elif len(contenders) ==1:
            #We have a winner:
            # print(f'DONE winner: {contenders[0]} ')
            return contenders[0]
        else:
            pass
            # We wish the reduce the contender size.
            # print(contenders)
            for index in range(len(contenders)//2):
                tmp_winner = start_competition(contenders[index], contenders[index+1], 500, verbose= False)[0]
                #This could be made more efficient, we want to pop the loser.
                if tmp_winner == contenders[index]:
                    contenders.pop(index+1)
                else:
                     contenders.pop(index)
                # print(contenders)

                
winner = initial_player
randomplayer =random_player("player_rand")

round_count = 0
# while True:
for i in range(3):
    print(f'Round {round_count}, winner: {winner}')
    round_count += 1
    
    if round_count % 5 == 0:
        start_competition(winner, randomplayer, 5000, verbose = True)
    winner = obtain_strongest_player(gen_mutated(12, winner.weight, winner.bias))
winner

Round 0, winner: p2
Round 1, winner: 10
Round 2, winner: 4


9


# Todo:
- optimize the reward function, make cost per move follow an exponential curve
- have  exploration build into mutations, decrease it over time
- unity pyhton integration.

In [15]:
# winner.save_npy()
# start_competition(initial_player, randomplayer, 1000, verbose = True)


# Unity integration

In [27]:
initial_weights = np.load("Player_85_weights.npy", allow_pickle=True)
initial_biases = np.load("Player_85_biases.npy", allow_pickle=True)
initial_player = neural_player( "p2", initial_weights, initial_biases)
start_competition(initial_player, randomplayer, 1000, verbose = True)



p2, score= -15058, wincount = 852, losscount = 148, drawcount = 0, avg moves: 20.69
player_rand, score= -26322, wincount = 148, losscount = 852, drawcount = 0, avg moves: 20.69
Took 3.3131 seconds


[p2, -15058]

In [ ]:

import time
import zmq

context = zmq.Context()
socket = context.socket(zmq.REP)
socket.bind("tcp://*:5555")
# random_pl = random_player("ron")
board = Board()
while True:
    #  Wait for next request from client
    message = socket.recv()
    print("Received request: %s" % message)
    unity_move = [ int(move) for move in message.decode().split(' ')[0].split(',')]
    print(unity_move)
    board.addmove(1, unity_move)
    print(board)
    
    # move = random_pl.choice(board)
    move = initial_player.choice(board)
    board.addmove_vector(2, move)
    #  Do some 'work'.
    #  Try reducing sleep time to 0.01 to see how blazingly fast it communicates
    #  In the real world usage, you just need to replace time.sleep() with
    #  whatever work you want python to do, maybe a machine learning task?
    time.sleep(1)

    #  Send reply back to client
    #  In the real world usage, after you finish your work, send your output here
    
    socket.send(f"{board.vector_to_cartesian(move)}".encode())

Received request: b'2,1,2 (UnityEngine.Transform)'
[2, 1, 2]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]

Received request: b'2,2,2 (UnityEngine.Transform)'
[2, 2, 2]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 0.]
  [2. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]

Received request: b'1,1,2 (UnityEngine.Transform)'
[1, 1, 2]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 1. 0.]
   [0. 1. 1. 0.]
   [0. 2. 0. 0.]
  [2. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]

Received request: b'3,